<a href="https://colab.research.google.com/github/namikazi25/Reinforcement-Learning-Codes/blob/main/Rl_frozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gymnasium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 7.7 MB/s eta 0:00:00


In [2]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make('FrozenLake-v1', render_mode='ansi')
# n_outputs = env.action_space.n

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
# obs, info = env.reset()
q_table = np.zeros((state_space_size, action_space_size))

In [5]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
gamma = 0.99

# exploration_rate = 1
# max_exploration_rate = 1
# min_exploration_rate = 0.01
# exploration_decay_rate = 0.001

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability
decay_rate = 0.005             # Exponential decay rate for exploration prob

In [ ]:
# total_episodes = 50000       # Total episodes
# learning_rate = 0.7          # Learning rate
# max_steps = 99               # Max steps per episode
# gamma = 0.95                 # Discounting rate

# # Exploration parameters
# epsilon = 1.0                 # Exploration rate
# max_epsilon = 1.0             # Exploration probability at start
# min_epsilon = 0.01            # Minimum exploration probability
# decay_rate = 0.005            # Exponential decay rate for exploration prob

In [11]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(num_episodes):
    # Reset the environment
    state = env.reset()[0]
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps_per_episode):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)

        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(q_table[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        #print(env.step(action))
        new_state, reward, done, turnicated, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        #q_table[state, action] = q_table[state, action] + learning_rate * (reward + gamma * np.max(q_table[new_state, :]) - q_table[state, action])

        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + gamma * np.max(q_table[new_state, :]))

        total_rewards += reward

        # Our new state is state
        state = new_state

        # If done (if we're dead) : finish episode
        if done == True:
            break

    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    # Exploration rate decay

    rewards.append(total_rewards)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
print ("Score over time: " +  str(sum(rewards)/num_episodes))
print(q_table)

********Average reward per thousand episodes********

1000 :  0.36600000000000027
2000 :  0.6850000000000005
3000 :  0.7060000000000005
4000 :  0.6810000000000005
5000 :  0.6700000000000005
6000 :  0.7060000000000005
7000 :  0.6680000000000005
8000 :  0.6960000000000005
9000 :  0.6970000000000005
10000 :  0.6940000000000005
Score over time: 0.6569
[[0.52617335 0.5046683  0.50514199 0.50451146]
 [0.33541766 0.32666494 0.34335121 0.48427916]
 [0.38500713 0.40896109 0.41404903 0.46149992]
 [0.32140257 0.22487655 0.27655846 0.45224634]
 [0.53860404 0.42672537 0.49372391 0.32329795]
 [0.         0.         0.         0.        ]
 [0.34186587 0.12214604 0.2125904  0.06617263]
 [0.         0.         0.         0.        ]
 [0.36306923 0.52676232 0.44200627 0.59092199]
 [0.42872843 0.6268435  0.56622437 0.42669557]
 [0.50391073 0.35763819 0.28011145 0.35085773]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40534236 0.52237455 0.73069243 0.34

In [12]:
# env.reset()[0]

for episode in range(5):
    state = env.reset()[0]
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        print(env.render())
        time.sleep(0.3)
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(q_table[state,:])

        new_state, reward, done, turnicate, info = env.step(action)

        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            clear_output(wait = True)
            print(env.render())
            if new_state == 15:
                print("We reached our Goal 🏆")
                time.sleep(3)
            else:
                print("We fell into a hole ☠️")
                time.sleep(3)
            clear_output(wait = True)

            # We print the number of step it took.
            print("Number of steps", step)

            break
        state = new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG

